package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	//"fmt"

	"github.com/brkss/golang-graphql/graph/model"
)

// CreateRecipeCategiory is the resolver for the CreateRecipeCategiory field.
func (r *mutationResolver) CreateRecipeCategiory(ctx context.Context, input *model.CreateRecipeCategoryInput) (*model.CreateCategoryResponse, error) {
	
	if input.Title == "" || input.Image == "" {
		err := "Invalid Data !"
		return &model.CreateCategoryResponse{
			Status: false,
			Message:  &err,
		}, nil
	}

	return &model.CreateCategoryResponse{
		Status: false,	
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type queryResolver struct{ *Resolver }
