// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCategoryResponse struct {
	Status   bool            `json:"status"`
	Message  *string         `json:"message"`
	Category *RecipeCategory `json:"category"`
}

type CreateRecipeCategoryInput struct {
	Title  string `json:"title"`
	Image  string `json:"image"`
	Active bool   `json:"active"`
}

type RecipeCategory struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Image  string `json:"image"`
	Active bool   `json:"active"`
}
