// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Status  bool    `json:"status"`
	Message *string `json:"message"`
	Token   *string `json:"token"`
}

type CreateCategoryResponse struct {
	Status   bool            `json:"status"`
	Message  *string         `json:"message"`
	Category *RecipeCategory `json:"category"`
}

type CreateRecipeCategoryInput struct {
	Title  string `json:"title"`
	Image  string `json:"image"`
	Active bool   `json:"active"`
}

type LoginUserInput struct {
	Ident    string `json:"ident"`
	Password string `json:"password"`
}

type RecipeCategory struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Image  string `json:"image"`
	Active bool   `json:"active"`
}

type RegisterUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
}
